Added a "hello_tiago" package
LiamWellacott/CDT2019-ERL pull request #40
Opened 2021-01-26 14:15 UTC by LiamWellacott

2021-01-27 11:51 UTC, erolley-parnell commented
I can run it, and it loads the robot inside the home, but both of the robot and the home are slightly off the ground?

2021-01-27 12:34 UTC, LiamWellacott commented
> I can run it, and it loads the robot inside the home, but both of the robot and the home are slightly off the ground?

The environment is off the ground and not centred, I had to find a starting position for the robot but wasn't sure how to find the z distance so just placed it enough off the ground to not clip into the flat's floor.

2021-01-28 10:23 UTC, erolley-parnell requested changes
Can you explore and see if you can translate the whole environment so that the environment has the same Z value as the origin?

2021-01-28 10:43 UTC, erolley-parnell approved these changes

2021-01-28 10:43 UTC, merged